export const SOFTWARE_LIST = [
  'Adobe Illustrator',
  'Adobe Photoshop',
  'Affinity Designer',
  'Corel Draw',
  'GIMP',
  'Adobe After Effects',
  'Adobe Premiere',
  'DaVinci Resolve',
  'ClipChamp',
  'Adobe InDesign',
  'Maya',
  'Blender',
  'Cinema 4D',
  'ZBrush',
  'Adobe Substance Painter',
  'Adobe XD',
  'Figma',
  'FontLab',
  'FontForge',
  'Glyphs',
  'Adobe Dreamweaver',
  'Adobe Acrobat',
  'Adobe Express',
  'Canva',
  'Gemini',
  'ChatGPT',
  'Claude',
  'Notion',
  'Slack',
  'Trello',
] as const

export type Software = (typeof SOFTWARE_LIST)[number]
