export const SPECIALTIES = [
  'Identidad visual y branding',
  'Diseño editorial',
  'Diseño de interfaz de usuario',
  'Diseño de experiencia de usuario',
  'Diseño web y frontend',
  'Diseño de empaque',
  'Diseño de información e infografía',
  'Diseño tipográfico',
  'Diseño de producto',
  'Diseño de producto digital',
  'Diseño para videojuegos',
  'Diseño instruccional y educativo',
  'Diseño para realidades inmersivas',
  'Diseño textil y de patrones',
  'Animación',
  'Diseño ambiental',
  'Señalética',
  'Diseño publicitario y marketing visual',
  'Ilustración digital y conceptual',
  'Diseño para producción impresa y preprensa',
  'Fotografía',
  'Videografía',
  'Diseño 3D',
  'Gestión del diseño',
  'Aspectos legales del diseño gráfico',
  'Dirección de arte',
  'Diseño de personajes',
] as const

export type Specialty = (typeof SPECIALTIES)[number]
