-- =============================================================
-- KNOTEN - WYSIWYG Support for Freelancer Resumen Profesional
-- =============================================================

-- The column `resumen_profesional` in `freelancer_profiles` is defined as TEXT.
-- PostgreSQL TEXT type supports arbitrary rich HTML content up to the 700 plaintext character limit.
-- No schema column type alteration is required as TEXT already handles HTML strings seamlessly.

COMMENT ON COLUMN public.freelancer_profiles.resumen_profesional IS 'Rich HTML text content generated by the WYSIWYG editor (max 700 plaintext characters)';
